-- MySQL Script generated by MySQL Workbench
-- Sun Dec  3 12:14:18 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema OwlArtistBD
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema OwlArtistBD
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `OwlArtistBD` DEFAULT CHARACTER SET utf8 ;
USE `OwlArtistBD` ;

-- -----------------------------------------------------
-- Table `OwlArtistBD`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OwlArtistBD`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `cargo` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OwlArtistBD`.`premium`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OwlArtistBD`.`premium` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nContaBancaria` VARCHAR(45) NULL,
  `anuncio` TINYINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OwlArtistBD`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OwlArtistBD`.`admin` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `permissao` TINYINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OwlArtistBD`.`usuarioComum`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OwlArtistBD`.`usuarioComum` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `seloVerificacao` TINYINT NULL,
  `email` VARCHAR(45) NULL,
  `senha` VARCHAR(45) NULL,
  `usuario_id` INT NOT NULL,
  `premium_id` INT NOT NULL,
  `admin_id` INT NOT NULL,
  PRIMARY KEY (`id`, `usuario_id`, `premium_id`, `admin_id`),
  INDEX `fk_usuarioComum_usuario_idx` (`usuario_id` ASC),
  INDEX `fk_usuarioComum_premium1_idx` (`premium_id` ASC),
  INDEX `fk_usuarioComum_admin1_idx` (`admin_id` ASC),
  CONSTRAINT `fk_usuarioComum_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `OwlArtistBD`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuarioComum_premium1`
    FOREIGN KEY (`premium_id`)
    REFERENCES `OwlArtistBD`.`premium` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuarioComum_admin1`
    FOREIGN KEY (`admin_id`)
    REFERENCES `OwlArtistBD`.`admin` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
