-- MySQL Script generated by MySQL Workbench
-- Sun Dec  3 16:38:12 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bancoowl
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bancoowl` DEFAULT CHARACTER SET utf8 ;

-- -----------------------------------------------------
-- Table `bancoOWL`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancoowl`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `senha` VARCHAR(100) NULL,
  `biografia` VARCHAR(200) NULL,
  `fotoPerfil` VARCHAR(200) NULL,
  `selo` TINYINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `mydb`.`publicacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancoowl`.`publicacao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `legenda` VARCHAR(45) NULL,
  `data` DATE NULL,
  `comentario` VARCHAR(300) NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`, `usuario_id`),
  INDEX `fk_publicacao_usuario_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_publicacao_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `bancoowl`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bancoOWL`.`compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancoowl`.`compra` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nContaBancaria` VARCHAR(45) NULL,
  `formaPagamento` VARCHAR(45) NULL,
  `cpf` VARCHAR(15) NULL,
  `comentario` VARCHAR(300) NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`, `usuario_id`),
  INDEX `fk_compra_usuario1_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_compra_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `bancoowl`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
